Repository smwu-ITPLE/ITPLE-frontend, pull requests merged in 2025-02, with the labels that each got.

#13 [feat] 홈화면~조문공간생성 디자인 수정 및 기능 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/smwuitple/maeumgil/api/LateApiService.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/Create1Fragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/Create2Fragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/Create3Fragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/Create4Fragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/DateTimePickerDialogFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/LoginFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/SignupFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/utils/RetrofitClient.kt
  app/src/main/java/com/smwuitple/maeumgil/utils/SessionManager.kt
  app/src/main/res/font/poppins_r.ttf
  app/src/main/res/layout/fragment_create1.xml
  app/src/main/res/layout/fragment_create2.xml
  app/src/main/res/layout/fragment_create3.xml
  app/src/main/res/layout/fragment_create4.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home2.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_sign_to_login.xml
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/layout/late_owner_card.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/network_security_config.xml
Labels: feat, design

#16 [feat] 조문공간 검색 구현
  app/src/main/java/com/smwuitple/maeumgil/api/ManageApiService.kt
  app/src/main/java/com/smwuitple/maeumgil/dto/request/LateRequest.kt
  app/src/main/java/com/smwuitple/maeumgil/dto/response/ManageResponse.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/HomeFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/PrivateMainFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/SearchFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/utils/RetrofitClient.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/xml/network_security_config.xml
Labels: feat

#18 [feat] 조문공간 조회 구현
  app/src/main/java/com/smwuitple/maeumgil/api/LateApiService.kt
  app/src/main/java/com/smwuitple/maeumgil/dto/response/LateResponse.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/PrivateMainFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/SearchFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/formatDateToKoreanStyle.kt
  app/src/main/java/com/smwuitple/maeumgil/utils/RetrofitClient.kt
  app/src/main/res/layout/fragment_private_main.xml
  app/src/main/res/xml/network_security_config.xml
Labels: feat

#23 [design] 마이페이지 디자인 추가 및 수정
  app/build.gradle.kts
  app/src/main/java/com/smwuitple/maeumgil/fragment/ManageDeleteFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/ManageMessageFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/MessageFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/OwnerListFragment.kt
  app/src/main/res/layout/chat_item.xml
  app/src/main/res/layout/fragment_chat_select.xml
  app/src/main/res/layout/fragment_manage_delete.xml
  app/src/main/res/layout/fragment_manage_fund.xml
  app/src/main/res/layout/fragment_manage_list.xml
  app/src/main/res/layout/fragment_manage_main.xml
  app/src/main/res/layout/fragment_manage_message.xml
  app/src/main/res/layout/fragment_manage_private.xml
  app/src/main/res/layout/fragment_manage_share.xml
  app/src/main/res/layout/fragment_message.xml
  app/src/main/res/layout/fragment_owner_list.xml
Labels: design

#24 [feat] 마이페이지 관리 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/smwuitple/maeumgil/DeepLinkActivity.kt
  app/src/main/java/com/smwuitple/maeumgil/api/LateApiService.kt
  app/src/main/java/com/smwuitple/maeumgil/api/ManageApiService.kt
  app/src/main/java/com/smwuitple/maeumgil/api/UserApiService.kt
  app/src/main/java/com/smwuitple/maeumgil/dto/response/ManageResponse.kt
  app/src/main/java/com/smwuitple/maeumgil/dto/response/UserResponse.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/ArchieveSuccessFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/Create3Fragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/Create4Fragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/HomeFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/LateListAdapter.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/LoginFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/ManageDeleteFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/ManageListFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/ManageMainFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/ManageShareFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/PrivateMainFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/SearchFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/SignupFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/utils/CustomCookieJar.kt
  app/src/main/java/com/smwuitple/maeumgil/utils/RetrofitClient.kt
  app/src/main/res/drawable/ic_share.png
  app/src/main/res/drawable/ic_trash.png
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_manage_list.xml
  app/src/main/res/layout/fragment_manage_main.xml
  app/src/main/res/layout/fragment_manage_share.xml
  app/src/main/res/layout/item_late_list.xml
  app/src/main/res/xml/network_security_config.xml
Labels: feat, design

#26 [mod] 서버없이 바로가기 임시 설정
  app/src/main/java/com/smwuitple/maeumgil/fragment/MainFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/SearchFragment.kt
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_search.xml
Labels: mod

#28 [feat] 조문공간 부의금 전송 및 조회
  app/src/main/java/com/smwuitple/maeumgil/api/LateApiService.kt
  app/src/main/java/com/smwuitple/maeumgil/api/ManageApiService.kt
  app/src/main/java/com/smwuitple/maeumgil/dto/request/LateRequest.kt
  app/src/main/java/com/smwuitple/maeumgil/dto/response/LateResponse.kt
  app/src/main/java/com/smwuitple/maeumgil/dto/response/ManageResponse.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/ManageFundFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/ManageListFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/OwnerAdapter.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/OwnerListFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/PayDetailAdapter.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/PaySummaryAdapter.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/Payment1Fragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/Payment2Fragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/PrivateMainFragment.kt
  app/src/main/res/drawable/default_card_background.xml
  app/src/main/res/drawable/selected_card_background.xml
  app/src/main/res/layout/fragment_manage_fund.xml
  app/src/main/res/layout/fragment_owner_list.xml
  app/src/main/res/layout/fragment_payment1.xml
  app/src/main/res/layout/fragment_payment2.xml
  app/src/main/res/layout/host_item.xml
  app/src/main/res/layout/item_pay_detail.xml
  app/src/main/res/layout/item_pay_summary.xml
  app/src/main/res/values/themes.xml
Labels: feat

#29 [feat] 카메라 기능 추가 및 HomeFragment 수정
  .idea/deploymentTargetSelector.xml
  .idea/gradle.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/smwuitple/maeumgil/fragment/CameraFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/HomeFragment.kt
  app/src/main/res/layout/fragment_camera.xml
  app/src/main/res/layout/fragment_home.xml
  gradle/libs.versions.toml
  gradlew
Labels: feat

#30 [feat] 조문 메시지 전송 및 조회
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/smwuitple/maeumgil/api/LateApiService.kt
  app/src/main/java/com/smwuitple/maeumgil/api/ManageApiService.kt
  app/src/main/java/com/smwuitple/maeumgil/dto/response/ManageResponse.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/Create4Fragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/ManageListFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/ManageMessageFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/MessageAdapter.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/MessageFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/PrivateMainFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/utils/RetrofitClient.kt
  app/src/main/res/layout/fragment_manage_message.xml
  app/src/main/res/layout/fragment_message.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/xml/network_security_config.xml
Labels: feat

#32 [feat] 마이페이지 조문공간 조회 기능
  app/src/main/java/com/smwuitple/maeumgil/fragment/LateListAdapter.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/ManageListFragment.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/ManagePrivateFragment.kt
  app/src/main/res/layout/fragment_manage_list.xml
  app/src/main/res/layout/fragment_manage_private.xml
Labels: feat

#35 [feat] 부의금 전송 카카오페이 송금 기능
  .idea/gradle.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/smwuitple/maeumgil/PaymentWebViewActivity.kt
  app/src/main/java/com/smwuitple/maeumgil/api/PaymentApiService.kt
  app/src/main/java/com/smwuitple/maeumgil/dto/request/PaymentRequest.kt
  app/src/main/java/com/smwuitple/maeumgil/dto/response/PaymentResponse.kt
  app/src/main/java/com/smwuitple/maeumgil/fragment/Payment2Fragment.kt
  app/src/main/java/com/smwuitple/maeumgil/utils/RetrofitClient.kt
  app/src/main/java/com/smwuitple/maeumgil/viewmodel/PaymentViewModel.kt
  app/src/main/res/layout/payment_webview.xml
Labels: feat
